### PR TITLE
[WIP]Fix #354: Fixing  Blob URL path entries for children when we rename a directory

### LINKED ISSUE #354: Update Blob URL path entries for children when we rename a directory
Found while fixing #353, we don't have recursive rename working for directories in BlobUtils.  When we do a rename for a path, we should be dealing with the fact that all children will have the old dir name in their cached path, but attempts to access them will use the new name.

The fix needs to happen in `FilerFilesystem.rename` and `BlobUtils.rename`.

### PR DESCRIPTION
**Pull request by evantsyferov**
working on bug 354

### CODE REVIEW

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 1]
```diff
@@ -173,33 +173,31 @@ define(function (require, exports, module) {
             stat(path, callback);
         });
     }
-
-    function rename(oldPath, newPath, callback) {
+   function rename(oldPath, newPath, callback) {
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Fix this indent please, you need 4-space indents in Brackets code.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 2]
```diff
@@ -173,33 +173,31 @@ define(function (require, exports, module) {
...
         oldPath = decodePath(oldPath);
         newPath = decodePath(newPath);
 
         function updateBlobURL(err) {
             if(err) {
                 return callback(_mapError(err));
             }
-
+        fs.refresh(callback);
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: The `refresh()` method doesn't live on the `fs` object.  It's part of the `FileSystemCache` module I linked you to previously.  You'll have to `require` it up on lines 7-15 with the other modules before you can use it.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 3]
```diff
@@ -173,33 +173,31 @@ define(function (require, exports, module) {
...
+        fs.reload();
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: These two lines are happening in the wrong place.  You likely want to do this down around 196 below.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 4]
```diff
@@ -173,33 +173,31 @@ define(function (require, exports, module) {
...
             // If this was a rename on a file path, update the Blob cache too
-            stat(newPath, function(err, stat) {
+            /*stat(newPath, function(err, stat) {
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Why are you removing this?  We'll need it to figure out if we're on a dir or file.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 5]
```diff
@@ -173,33 +173,31 @@ define(function (require, exports, module) {
...
-                callback();
-            });
+                } 
+                callback(); 
+            });*/
         }
-
-        fs.rename(oldPath, newPath, _wrap(updateBlobURL));
-    }
+         fs.rename(oldPath, newPath, _wrap(updateBlobURL));
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Indent is wrong here.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 6]
```diff
@@ -182,7 +183,7 @@ define(function (require, exports, module) {
             if(err) {
                 return callback(_mapError(err));
             }
-
+
```
Comment (Pomax) [inline src/filesystem/impls/filer/FilerFileSystem.js]: please remove this =)

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 7]
```diff
@@ -192,14 +193,14 @@ define(function (require, exports, module) {
...
+                } 
+                FileSystemCache.refresh(callback);
+                LiveDevMultiBrowser.reload();
+                callback(); 
             });
         }
-
         fs.rename(oldPath, newPath, _wrap(updateBlobURL));
-    }
+    }
```
Comment (Pomax) [inline src/filesystem/impls/filer/FilerFileSystem.js]: please remove this too =)

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 8]
```diff
@@ -194,9 +193,15 @@ define(function (require, exports, module) {
...
                 } 
-                FileSystemCache.refresh(callback);
-                LiveDevMultiBrowser.reload();
-                callback(); 
+                FileSystemCache.refresh(function(){
+                  if(err) {
+                    callback(err);
+                    return;
+                  } 
+                        LiveDevMultiBrowser.reload();
```
Comment (Pomax) [inline src/filesystem/impls/filer/FilerFileSystem.js]: looks like the indentation went wrong here.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 9]
```diff
@@ -173,7 +175,6 @@ define(function (require, exports, module) {
             stat(path, callback);
         });
     }
-
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Add this blank line back again, please.  It's a good idea not to make changes in a file that aren't related to what you're working on, so the the `git blame` info stays consistent.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 10]
```diff
@@ -182,7 +183,6 @@ define(function (require, exports, module) {
             if(err) {
                 return callback(_mapError(err));
             }
-
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Same thing here, you can add this back.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 11]
```diff
@@ -193,11 +193,15 @@ define(function (require, exports, module) {
                     BlobUtils.rename(oldPath, newPath);
                     BrambleEvents.triggerFileRenamed(oldPath, newPath);
                 }
-
-                callback();
+                FileSystemCache.refresh(function(){
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Add one blank line above this, so that it stands out from the `if` block above it.

Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Also, your callback function needs to accept an `err` object, so that you know if it worked or failed:

```js
FileSystemCache.refresh(function(err){
```

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 12]
```diff
@@ -193,11 +193,15 @@ define(function (require, exports, module) {
...
+                  if(err){    
+                    return callback(err);
+                  }
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: These 3 lines (197-199) need to get indented a further 4-spaces.  Also, line 198 needs to use 4-space indents.  Fix your editor when working on this file to use 4-spaces vs. 2-spaces for your tab indents.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 13]
```diff
@@ -193,11 +193,15 @@ define(function (require, exports, module) {
...
+                    LiveDevMultiBrowser.reload();
+                    callback();
+                })();
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: This should just be `});`, which will a) close the callback function you started on 196; and b) close the invocation of the `refresh()` method.  You don't need a further invocation.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 14]
```diff
@@ -193,11 +193,15 @@ define(function (require, exports, module) {
...
             });
         }
-
```
Comment (humphd) [inline src/filesystem/impls/filer/FilerFileSystem.js]: Revert this.

**Comment by humphd** [comment]
@evantsyferov how is this going? Can you fix the issues I mentioned above?  If you need help, please see my in/after class.

**Comment by evantsyferov** [comment]
@humphd I did the fixes you requested. But I have ran into a problem with running thimble locally. I have tried vagrant up --provision and vagrant destroy & vagrant up. It gets stuck on the loading project page.When I inspect the page I get errors from brackets:    
screenshot 60

**Comment by humphd** [comment]
For the code you're writing, you can skip Thimble altogether and just run Brackets by doing `npm start` and then going to `http://localhost:8000/src/hosted.html`.  That will just load the editor part, which is where your code changes live, and you should be able to test it that way.

The problem you're seeing above comes from changes to how Thimble is using the Bracket's client API, and it needs to be rebuilt.  You can run `npm run build` in Brackets before you do `npm start` to create it.

**Comment by evantsyferov** [comment]
I tested the code and it fixed the problem here is a screencast gif of the testing: 
0 2i354g2

File: src/config.json [hunk 15]
```diff
@@ -37,59 +37,50 @@
     },
```
Comment (humphd) [inline src/config.json]: You can run `git checkout master src/config.json` to get rid of this change.

File: src/config.json [hunk 16]
```diff
@@ -37,50 +37,59 @@
...
         "grunt-contrib-less": "1.4.0",
         "grunt-contrib-requirejs": "0.4.1",
         "grunt-contrib-uglify": "2.1.0",
-        "grunt-contrib-watch": "0.4.3",
-        "grunt-eslint": "18.1.0",
-        "grunt-exec": "^1.0.1",
-        "grunt-jasmine-node": "0.1.0",
-        "grunt-lib-phantomjs": "0.3.0",
+        "grunt-git": "^0.3.4",
+        "grunt-npm": "git://github.com/sedge/grunt-npm.git#branchcheck",
```
Comment (Pomax) [inline src/config.json]: there is no guarantee this repo will even exist an hour from now, can we point to an actual npm-hosted project instead?

Comment (humphd) [inline src/config.json]: NOTE: we can do that, but not in this bug.  This bug isn't actually changing any npm deps, it just got a cached version of what's in `package.json` due to a build config (which no longer happens on `master` btw).

Comment (Pomax) [inline src/config.json]: ah, in that case disregard my request here.

File: src/filesystem/impls/filer/FilerFileSystem.js [hunk 17]
```diff
@@ -46,7 +46,8 @@ define(function (require, exports, module) {
     function _mapError(err) {
         if (!err) {
             return null;
-        }
+         }
```
Comment (Pomax) [inline src/filesystem/impls/filer/FilerFileSystem.js]: why is there an extra space here now? `npm test` should have flagged this as being the wrong indentation.

**Comment by humphd** [comment]
Looks great @evantsyferov, merged!

**Comment by humphd** [comment]
image

It looks like this caused a regression, and @flukeout noticed that `master` wasn't starting anymore.  I've [pushed a fix](https://github.com/mozilla/brackets/commit/2972efbdfff4324d5f3ed10beb742551048a8673).  @gideonthomas if you see any problems with this, I can do another PR, but this gets it loading again.  I think it's a load timing bug in how `require` is trying to set up the modules, and we were trying to load the `LiveDevMultiBrowser` too early, before the `FileSystem` was fully setup and had that method.

I've tested this locally and it seems to work well. It actually makes more sense to not have the fs code interacting with live dev.

@evantsyferov did you not hit this when you tested locally?  I'm surprised you didn't have this issue with your changes and the screencast you posted above.

**Comment by humphd** [comment]
https://github.com/mozilla/brackets/issues/676 is also about this regression.
