### PR TITLE
Switch to rimraf module from rm for Windows compat, fix #764

### LINKED ISSUE #764: Failed at the bramble@1.9.0-0 build script 'grunt build-browser
### Description

Trying to setup Bramble on my local machine.

### Steps to Reproduce

1. npm install --no-optional / good
2. npm run build / failed

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bramble@1.9.0-0~prebuild: bramble@1.9.0-0
6 silly lifecycle bramble@1.9.0-0~prebuild: no script for prebuild, continuing
7 info lifecycle bramble@1.9.0-0~build: bramble@1.9.0-0
8 verbose lifecycle bramble@1.9.0-0~build: unsafe-perm in lifecycle true
9 verbose lifecycle bramble@1.9.0-0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;d:\LOCALHOST\Bramble\brackets\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Installed\Audio\LiquidSonics\Reverberate (x64)\Resources;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;D:\PROGRAMS\INTERNET\Youtube-dl\;D:\PROGRAMS\INTERNET\Wget\;C:\Program Files (x86)\Livestreamer;C:\Program Files (x86)\VideoLAN\;D:\PROGRAMS\Dev\Zeal Dev\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;c:\Users\anephew\AppData\Local\Android\sdk\platform-tools\;D:\PROGRAMS\INTERNET\WinSCP\;c:\Program Files (x86)\Installed\Dev\Git\cmd;D:\PROGRAMS\Dev\Brackets 0.45\command;C:\Program Files (x86)\Installed\Other\Skype\Phone\;C:\Program Files\nodejs\;C:\Ruby23-x64\bin;C:\Users\anephew\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\HMA! Pro VPN\bin;C:\Users\anephew\AppData\Local\atom\bin;C:\Users\anephew\AppData\Local\Microsoft\WindowsApps;C:\Users\anephew\AppData\Roaming\npm
10 verbose lifecycle bramble@1.9.0-0~build: CWD: d:\LOCALHOST\Bramble\brackets
11 silly lifecycle bramble@1.9.0-0~build: Args: [ '/d /s /c', 'grunt build-browser' ]
12 silly lifecycle bramble@1.9.0-0~build: Returned: code: 3  signal: null
13 info lifecycle bramble@1.9.0-0~build: Failed to exec build script
14 verbose stack Error: bramble@1.9.0-0 build: `grunt build-browser`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid bramble@1.9.0-0
16 verbose cwd d:\LOCALHOST\Bramble\brackets
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error bramble@1.9.0-0 build: `grunt build-browser`
22 error Exit status 3
23 error Failed at the bramble@1.9.0-0 build script 'grunt build-browser'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the bramble package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt build-browser
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs bramble
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls bramble
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

image

Windows 10 x64 1703 (15063.296)

### PR DESCRIPTION
**Pull request by humphd**
This should fix things.

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -407,7 +407,7 @@ module.exports = function (grunt) {
         exec: {
             localize: 'node scripts/properties2js',
             'localize-dist': 'node scripts/properties2js dist',
-            'clean-nls': 'rm -fr src/nls && git checkout -- src/nls'
+            'clean-nls': 'node_modules/.bin/rimraf src/nls && git checkout -- src/nls'
```
Comment (Pomax) [inline Gruntfile.js]: I would *strongly* suggest making this an npm script and calling `npm run clean-nls` here, so that there is no guess work about where `rimraf` lives. In NPM scope, it lives "wherever npm has been told to put it", which can't break, whereas this will break if someone's using a custom npm version, or even if npm changes the indexing location again, like it did going from npm2 to npm3.

**Comment by humphd** [comment]
OK, moved things to `package.json`.

@gideonthomas can you look at this too?

File: package.json [hunk 2]
```diff
@@ -56,16 +56,18 @@
...
         "tar-fs": "^1.15.1"
     },
     "scripts": {
         "localize": "node scripts/properties2js",
+        "localize-dist": "node scripts/properties2js dist",
+        "unlocalize": "rimraf src/nls && git checkout -- src/nls",
         "postinstall": "grunt install",
         "build": "grunt build-browser",
-        "preproduction": "grunt build-browser-compressed && grunt unlocalize",
+        "preproduction": "grunt build-browser-compressed && npm run localize",
```
Comment (humphd) [inline package.json]: Good catch, fixed in new commit.  Good to go now?
