### PR TITLE
fix: Color picker only works for an existing color

### LINKED ISSUE #493: Color picker only works for an existing color
In a css file, start typing in `color:` and then press `Cmd+E`. It tries to (unsuccessfully) open up a Quick Edit widget instead of a color picker.

Now type in `red` or some other color and now press `Cmd+E` - it opens up the color picker.

Requiring a color to already be present to enable the color picker is some pretty bad UX. Also, having a Quick Edit for CSS does not really make a lot of sense we don't really do links to files in CSS (we may want to support this with `@import` but we should special case that). 

Instead, we should always show the color picker for tags such as `color`, `background`, `background-color`, `font`, `font-color`, etc. as soon as the `:` is inserted.

### PR DESCRIPTION
**Pull request by aayushsanghavi**
Fixes #493

Current status: Color picker pops up on ctrl + e after a CSS style name with type color.

color-picker

What still needs fixing:
- ~~Syntax to include the CSSProperties.json file from CSSCodeHints.~~
- ~~Color picker works only if at least one CSS rule with type color already exists in the CSS file. Without that it gives an error in the console " TypeError: originalArray is null" which occurs at "InlineColorEditor.js:234:9"!~~
- ~~After choosing a color value from the color picker, anything and everything after the color value gets replaced (be it the closing curly braces or any CSS rues below that one)~~

### CODE REVIEW

**Comment by Pomax** [comment]
Hi @aayushsanghavi can you run `npm test` locally, so that the PR doesn't fail over easy to fix javascript formatting/conventions?

**Comment by aayushsanghavi** [comment]
@Pomax my bad. It slipped out. Won't happen again.

**Comment by aayushsanghavi** [comment]
Could you please help me with the 3 issues I'm facing currently. I don't know how to go about them.

File: src/extensions/default/InlineColorEditor/main.js [hunk 1]
```diff
@@ -27,7 +27,9 @@ define(function (require, exports, module) {
     var EditorManager       = brackets.getModule("editor/EditorManager"),
         ExtensionUtils      = brackets.getModule("utils/ExtensionUtils"),
         InlineColorEditor   = require("InlineColorEditor").InlineColorEditor,
-        ColorUtils          = brackets.getModule("utils/ColorUtils");
+        ColorUtils          = brackets.getModule("utils/ColorUtils"),
+	 CSSProperties = brackets.getModule("text!extensions/default/CSSCodeHints/CSSProperties.json"),
```
Comment (Pomax) [inline src/extensions/default/InlineColorEditor/main.js]: some misalignment happened here.

File: src/extensions/default/InlineColorEditor/main.js [hunk 2]
```diff
@@ -39,41 +41,29 @@ define(function (require, exports, module) {
...
         cursorLine = hostEditor.document.getLine(pos.line);
 
-        // Loop through each match of colorRegEx and stop when the one that contains pos is found.
-        do {
-            match = colorRegEx.exec(cursorLine);
-            if (match) {
-                start = match.index;
-                end = start + match[0].length;
+        // Make a copy of cursorLine after removing spaces and ":" so that we can check for it in properties
+        cursorLine2 = cursorLine.replace(/\s/g,'');
```
Comment (Pomax) [inline src/extensions/default/InlineColorEditor/main.js]: does `cursorLine` get reconsulted later? If not, there is no need to define a `cursorLine2` here, just recycle `cursorLine`. Alternatively, it might make more sense to name this variable after what you're actually grabbing:
```
cssPropertyName = cursorLine.split(':')[0].trim();
```
and then use that in the `properties[cssPropertyName]` check.

File: src/extensions/default/InlineColorEditor/main.js [hunk 3]
```diff
@@ -39,41 +41,29 @@ define(function (require, exports, module) {
...
+        cursorLine2 = cursorLine2.replace(":", "");
+        
+        if (properties[cursorLine2]) {
+            if (properties[cursorLine2].type === "color") {
+                pos.ch = cursorLine.length-1;
+                endPos = {line: pos.ch, ch: cursorLine[cursorLine.length]};
+                console.log(endPos);
```
Comment (Pomax) [inline src/extensions/default/InlineColorEditor/main.js]: rogue console.log?

File: src/extensions/default/InlineColorEditor/main.js [hunk 4]
```diff
@@ -39,41 +41,29 @@ define(function (require, exports, module) {
...
+                marker = hostEditor._codeMirror.markText(pos, endPos);
+                return {
+                    color: "white",
+                    marker: marker
+                };
             }
-        } while (match && (pos.ch < start || pos.ch > end));
-
-        if (!match) {
+        }
```
Comment (Pomax) [inline src/extensions/default/InlineColorEditor/main.js]: `} else {`

**Comment by aayushsanghavi** [comment]
Thanks for the review @Pomax

**Comment by flukeout** [comment]
Checking this now

**Comment by flukeout** [comment]
I'm unable to get this running in the same way as your gif. When I try out your branch and then type ``color: `` and hit Command E, i get the following JS error...

image

...and the color picker does not show up. Are there any special steps I need to take when testing this?

**Comment by aayushsanghavi** [comment]
@flukeout yes there are issues to be handled yet. You will have to write a style of type color first.
Say for example - 
p {
  color: red; (or any other style of type color)
  <then write any other style that might be of type color and press ctrl + E>
}
In the description of the PR, I've mentioned the issues that need to be fixed.

Thanks for trying it out!

**Comment by aayushsanghavi** [comment]
@flukeout were you able to get the color picker working?

**Comment by flukeout** [comment]
Hi @aayushsanghavi just tested again, and found the following problem, if you use the colorpicker on an existing color, it adds the value at the end of the color...

colorpicker-broken

**Comment by aayushsanghavi** [comment]
Oh okay. So what would you suggest I should do in order to fix this?

**Comment by aayushsanghavi** [comment]
I made a lot changes in the code.
Current status and improvements -
- When we press ctrl + e on a CSS rule that is of type color, the marker sets correctly around the color value.
- Earlier, after selecting a value from the color picker, everything after that color value was replaced by the color value. Now, only the color value changes and everything else remains unchanged.
- For a new CSS rule of type color the default color picker value is white but for a CSS rule with an already set color value, the default value on the color picker pop up is its current value

color-picker2

To test this, be sure to have at least on CSS rule of type color.

Problem that still persists -
Color picker works only if at least one CSS rule with type color already exists in the CSS file. Without that it gives an error in the console " TypeError: originalArray is null" which occurs at "InlineColorEditor.js:234:9"

@flukeout @Pomax please test it and give your feedback

File: src/extensions/default/InlineColorEditor/main.js [hunk 5]
```diff
@@ -27,7 +27,9 @@ define(function (require, exports, module) {
     var EditorManager       = brackets.getModule("editor/EditorManager"),
         ExtensionUtils      = brackets.getModule("utils/ExtensionUtils"),
         InlineColorEditor   = require("InlineColorEditor").InlineColorEditor,
-        ColorUtils          = brackets.getModule("utils/ColorUtils");
+        ColorUtils          = brackets.getModule("utils/ColorUtils"),
+	 CSSProperties       = require("text!CSSProperties.json"),
+        properties          = JSON.parse(CSSProperties);
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: This will will throw if that file has any syntax errors.  I think you should do this in a `try` block on the first instance where you need it.

File: src/extensions/default/InlineColorEditor/main.js [hunk 6]
```diff
@@ -39,41 +41,43 @@ define(function (require, exports, module) {
...
         cursorLine = hostEditor.document.getLine(pos.line);
 
-        // Loop through each match of colorRegEx and stop when the one that contains pos is found.
-        do {
-            match = colorRegEx.exec(cursorLine);
-            if (match) {
-                start = match.index;
-                end = start + match[0].length;
+        // Make a copy of cursorLine after removing spaces and ":" so that we can check for it in properties
+        cssPropertyName = cursorLine.split(':')[0].trim();
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: This also seems fragile to me.  Is `cursorLine` always guaranteed to be non-null?

File: src/extensions/default/InlineColorEditor/main.js [hunk 7]
```diff
@@ -39,41 +41,43 @@ define(function (require, exports, module) {
...
+
+        if (properties[cssPropertyName]) {
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: Flip your logic here and return early, so you don't have to indent a huge block of code:

```js
if (!properties[cssPropertyName]) {
    return null;
}

// Now do the rest of your code here, without indenting
```

File: src/extensions/default/InlineColorEditor/main.js [hunk 8]
```diff
@@ -39,41 +41,43 @@ define(function (require, exports, module) {
...
+            if (properties[cssPropertyName].type === "color") {
+                colon = cursorLine.indexOf(":");
+                semiColon = cursorLine.indexOf(";");
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: Because `colon` and `semiColon` are positions in the string, it might make more sense to name them `colonPos` and `semiColonPos`

File: src/extensions/default/InlineColorEditor/main.js [hunk 9]
```diff
@@ -39,41 +41,43 @@ define(function (require, exports, module) {
...
+                    colorValue = cursorLine.substring(hash, semiColon);
+                  } else {
+                    var colorString = cursorLine.substring(colon, semiColon);
+                    var firstCharacter = colorString.search(/\w/);
+                    pos.ch = colon + firstCharacter;
+                    colorValue = cursorLine.substring(colon + firstCharacter, semiColon);
+                  }
+                  endPos = {line: pos.line, ch: semiColon};
+                } else {
+                  pos.ch =  colon + 1;
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: Extra space after `=`, please remove.

File: src/extensions/default/InlineColorEditor/main.js [hunk 10]
```diff
@@ -39,41 +41,43 @@ define(function (require, exports, module) {
...
+                  endPos = {line: pos.line, ch: cursorLine.length};
+                  colorValue = "white";
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: If `white` is your default colour value, make it a top-level variable in the module, e.g., `var DEFAULT_COLOR = "white";` and use that here.

File: src/extensions/default/InlineColorEditor/CSSProperties.json [hunk 11]
```diff
@@ -0,0 +1,230 @@
+{
+    "align-content":               {"values": ["center", "flex-end", "flex-start", "space-around", "space-between", "stretch"]},
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/CSSProperties.json]: Is it possible for us to reduce the size of this to only those properties that actually need the color picker?  It seems like a waste to have all of these here, when there are very few that actually need to display the color picker.

**Comment by aayushsanghavi** [comment]
Thank you so much @humphd for your feedback. I agree with your suggestions.
I'll get back to you soon with all the changes you've proposed.

File: src/extensions/default/InlineColorEditor/CSSProperties.json (hunk 11 above)
Comment (aayushsanghavi) [inline src/extensions/default/InlineColorEditor/CSSProperties.json]: So should I keep only those properties that are of type color and remove the rest. Also, in that case should I rename the file to ColorProperties.json?

Comment (humphd) [inline src/extensions/default/InlineColorEditor/CSSProperties.json]: On lines 50, 51 of `src/extensions/default/InlineColorEditor/main.js` you basically have to do 2 `if` checks to narrow things down, so yes, I'd just preemptively do this and only include the properties you know you care about for color in the file.  Yes, renaming the file is probably good.

File: src/extensions/default/InlineColorEditor/main.js (hunk 6 above)
Comment (aayushsanghavi) [inline src/extensions/default/InlineColorEditor/main.js]: Agreed, but even when it is null, and we try to use any Quick Edit options, it gives an error saying no such options are available.
Should I put an if condition to check if it is non-null?

File: src/extensions/default/InlineColorEditor/main.js (hunk 5 above)
Comment (aayushsanghavi) [inline src/extensions/default/InlineColorEditor/main.js]: I didn't understand the part "on the first instance where you need it". Could you please elaborate?

**Comment by aayushsanghavi** [comment]
@humphd the edit you suggested in the file InlineColorEditor.js worked. Thanks a lot! I was stuck on it since so many days.

File: src/extensions/default/InlineColorEditor/main.js (hunk 6 above)
Comment (aayushsanghavi) [inline src/extensions/default/InlineColorEditor/main.js]: I added an if condition to check if it is non-null as follows -
`if (!cssPropertyName || !properties[cssPropertyName]) {
    return null;
}
`

**Comment by aayushsanghavi** [comment]
After @humphd's review and suggestions, the problem of having a css rule of type color to enable color picking is now resolved. Here's how it looks now -

color-picker3

@flukeout could you please test it?

**Comment by flukeout** [comment]
Definitely, testing now.

**Comment by flukeout** [comment]
Oh yeah instead of ``For issue #493`` in your description, if you change it to say exactly ``Fixes #493`` - then the associated issue will automatically be closed when this PR is merged.

**Comment by aayushsanghavi** [comment]
Yeah @flukeout. Thanks for reminding me. I had written that initially because the PR was under work.

**Comment by flukeout** [comment]
Hi @aayushsanghavi - the color picker no longer works when the cursor is over an existing color in a ``background:`` rule for example...

image

Nor does it work within ``border:`` 

image

I'm guessing this is the case for any other rule that might have a color within in.

**Comment by aayushsanghavi** [comment]
@flukeout that is because those styles aren't in the ColorProperties.json file

**Comment by flukeout** [comment]
@aayushsanghavi The colorpicker works on thimble.mozilla.org in the circumstances I listed. I don't think it's a good idea to stop supporting those use cases in favor of introducing a new one. We should only introduce the change in this PR if it also allows the old use cases to work.

**Comment by flukeout** [comment]
For reference, here's how it works currently...

picker

So it should still be able to change a color within a longer string that makes up a rule.

Are you adding rule by rule definitions in ColorProperties.json basically? If so, there are probably more like outline, box-shadow, etc.

How did the old colorpicker work then? It didn't need to know the rule that it was used within, just that you had your cursor on an existing color right? Can we preserve that functionality and only reoly on ColorProperties.json when we are are not currently editing a color?

**Comment by aayushsanghavi** [comment]
@flukeout I'm not hardcoding anything, I'm just checking a list of css rules of type color to decide if the color picker should pop up. I was doing it the same way earlier, only that the UX was very messed up.
I remember having seen a regex for checking any color value (hex, string, etc), in some file. I could maybe change my logic a bit and use that regex to figure out if the value is a color or not but I guess we'll still have to maintain a list of all css rules that can have a color argument so that we don't allow the color picker to pop up in cases when we just mention a color value or add it on a rule that can't take color values.

**Comment by flukeout** [comment]
It seems you are hardcoding the CSS rules for which the colorpicker is able to be used in the ``ColorProperties.json`` file, or am I wrong?

**Comment by aayushsanghavi** [comment]
Also, could you tell me if it is safe to assume, that no matter what, a color value is always specified at the end of the css rule.
For eg - `border: solid 2px black;` or `background: #fff` (#fff is still technically specified last).

**Comment by flukeout** [comment]
``border: pink 2px solid;`` is still valid CSS, so the color rule doesn't have to show up last.

**Comment by aayushsanghavi** [comment]
In my earlier comment, by hardcoding, I meant not checking separately for each css rule of type color.
You're right though.

**Comment by aayushsanghavi** [comment]
Oh okay. Then I would have to use the color regex and check if any values of the css rule is a color value then make the color-picker pop up.

**Comment by flukeout** [comment]
I think ideally, the logic should go as follows if someone tries to open the colorpicker...

* First, check if the cursor is within an existing color
  * I guess this is the regex check you were talking about?
  * If if it, open colorpicker
* If it is not, check if I am editing a value for a specific set of CSS rules
  * This is where we can check the ``.json`` file
  * If I am within one of the valid rules, then show the colorpicker

Does this order make sense and seem correct to you?

**Comment by aayushsanghavi** [comment]
@flukeout it looks perfect to me. I'll start working on it from tomorrow then. Thank you so much for helping out.

**Comment by flukeout** [comment]
Yeah, I think we should use the existing code for the colorpicker to make sure that it works for all of the old use-cases, and then add in the new functionality for cases when there isn't a color yet within a rule that could accept a color.

However, now that I'm thinking about this, it kind of raises a problem if we ever want to add other QuickEdit menus. For example, if we build a fancy QuickEdit menu for the ``border`` property that gives you a bunch of color, stroke and type options we would need to decide which QuickEdit menu to open, the colorpicker or the hypothetical borderpicker.

**Comment by humphd** [comment]
As an aside, the screencast in https://github.com/mozilla/brackets/pull/641#issuecomment-289920223 shows some odd overlapping of colour names/swatches in your browser.  What are you using?  I wonder if we should file that separately.

**Comment by aayushsanghavi** [comment]
@humphd I am using Firefox Nightly. I couldn't spot the color overlap, how should I look for it in that gif?

**Comment by aayushsanghavi** [comment]
@flukeout @humphd I've implemented it according to the logic discussed yesterday. Here's how it works now -

color-picker4

Please test it and let me know if we're missing something.
Thanks!

**Comment by flukeout** [comment]
Ok, testing now!

**Comment by flukeout** [comment]
Hey @aayushsanghavi  this is coming along really great, one request - is it possible to preserve the space before the color after the rule if there already is one before using the colorpicker? Right now it removes that space. Here's what I mean...

space-picker

**Comment by aayushsanghavi** [comment]
@flukeout thank you so much for trying it out. And yeah I get what you're saying. I actually tried a lot to fix that so that the level of UX is maintained but I couldn't figure out. I even tried the Trial and Error approach to get it to work somehow but it didn't work.
If you could look into the code and suggest something I could try that.

**Comment by aayushsanghavi** [comment]
@flukeout if we could somehow add another space when we type a new css rule of type color, our issue can be solved. Is there any way to do that? Something like `hostEditor.document.setLine(lineNumber, string)` ?

**Comment by humphd** [comment]
@hkirat is doing similar work in https://github.com/mozilla/brackets/pull/651/files#diff-12ec682d75836bdc488d42abbe212a30R71 and might have ideas for you, or code you can borrow to solve the spaces issue.

**Comment by aayushsanghavi** [comment]
Thanks @humphd but I can't see his name on the list of members on Mozilla Chat. I guess he isn't online.
I'll contact him when possible.

File: src/extensions/default/InlineColorEditor/main.js [hunk 12]
```diff
@@ -59,7 +67,45 @@ define(function (require, exports, module) {
...
+                    if (colorRegEx.test(colorValue)) {
+                        firstCharacterPos = cursorLineSubstring.search(/\S/);
+                        pos.ch = colonPos + 1 + firstCharacterPos;
+                        endPos = {line: pos.line, ch: semiColonPos};
+                    } else {
+                        return null;
+                    }
+                } else {
+                    // edit the color value of a new css rule
+                    pos.ch = colonPos + 1;
```
Comment (hkirat) [inline src/extensions/default/InlineColorEditor/main.js]: Doesn't necessarily have to be colonPos + 1.
It should really at the end of this line. (Assuming the person has only included spaces after the colon)

File: src/extensions/default/InlineColorEditor/main.js [hunk 13]
```diff
@@ -59,7 +67,45 @@ define(function (require, exports, module) {
...
+
+            if (!cssPropertyName || !properties[cssPropertyName]) {
+                return null;
+            }
+
+            if (properties[cssPropertyName].type === "color") {
+                colonPos = cursorLine.indexOf(":");
+                semiColonPos = cursorLine.indexOf(";");
+                if (semiColonPos !== -1) {
+                    // edit the color value of an existing css rule
```
Comment (hkirat) [inline src/extensions/default/InlineColorEditor/main.js]: I dont think you need this portion of your code.
Reason : If there is a match the code above will take care of it and control will never reach here anyways.
What you are doing here is assuming that if there is a semi colon at the end of your tag, there has to be a color matching the regex before it.
However that is not the case.
I may write
```css
color : ;
``` 
and press Ctrl + E after placing the cursor before the semi colon. That is the case that you need to tackle here.

**Comment by hkirat** [comment]
Hi @aayushsanghavi 
Nice work with this P.R.
I have added a few comments related to how you can fix your problem. You should be able to see them once the admins approve them. 
Hope they help out.

File: src/extensions/default/InlineColorEditor/main.js (hunk 13 above)
Comment (aayushsanghavi) [inline src/extensions/default/InlineColorEditor/main.js]: @hkirat thanks for pointing out the possibility of `color : ;`. However, I do need that code.
Reason: The previous code allows the user to change the color value only if the cursor is on the color value. It doesn't allow the user to use the color picker by pressing ctrl + e anywhere on the line of a CSS rule of type color and change the color value. We need that functionality.

**Comment by aayushsanghavi** [comment]
@hkirat we're facing this [issue](https://github.com/mozilla/brackets/pull/641#issuecomment-290172690). Also, have a look at [this](https://github.com/mozilla/brackets/pull/641#issuecomment-290183063).
Can you help out with this?

File: src/extensions/default/InlineColorEditor/main.js (hunk 12 above)
Comment (aayushsanghavi) [inline src/extensions/default/InlineColorEditor/main.js]: In this case too, we'd rather have something like `color:red;`than `color:<lots of spaces>red;`.

Comment (hkirat) [inline src/extensions/default/InlineColorEditor/main.js]: Hey.

I understand that a single space looks better visually.
But if the user has more than one space present, he/she must see that many number of spaces after he/she presses Ctrl + E 
Eg : If a user sees this
```js
color:<lots of spaces>red;
```
and places his/her cursor on red and presses Ctrl+E, what he expects is the popup to flow down with the number of spaces retained.
You are limiting the space to one in all cases. 
That is what @flukeout has pointed out in [this](https://github.com/mozilla/brackets/pull/641#issuecomment-290172690) issue.
If the user has a space, it should be retained.

Comment (aayushsanghavi) [inline src/extensions/default/InlineColorEditor/main.js]: The issue is that we need to have a space after the colon when the user types a new css rule. Currently the status is that if I'm writing a new CSS rule, I can't preserve the space that comes by default after the colon. The marker replaces that space with a color value. Instead we need something way to add another space to that line and then replace that space with the color value because the marker doesn't work for a position, it needs a string to replace.
Current - `color:red;` and we need `color: red`.

Comment (hkirat) [inline src/extensions/default/InlineColorEditor/main.js]: If you go through @flukeout 's comment again it says
```
Hey @aayushsanghavi this is coming along really great, one request - is it possible to preserve the space before the color after the rule **if there already is one before using the colorpicker?** Right now it removes that space.
```
So what you need to do is preserve the number of spaces, not add one.

Comment (flukeout) [inline src/extensions/default/InlineColorEditor/main.js]: I think we'd be OK to just make sure we end up with one space after the text that we add the new color value to. If someone adds in 3 spaces before firing up the colorpicker, it would sort of be a benefit to them to format the CSS in a better way.

I just want to avoid removing a space if it's already added.

**Comment by aayushsanghavi** [comment]
@flukeout is there any way in which we could allow the marker to replace an empty string with a color value? In the case of -

atcolonpos 2

the color value we select doesn't show up on the screen. This is because the start position and end position of the marker are the same, hence it returns an empty string which causes this problem.

**Comment by flukeout** [comment]
Hey @aayushsanghavi I'm not too familiar with the code, so I'm not sure. Another option might be that if you open the colorpicker and nothing is there, you immediately insert #FFFFFF into the editor and highlight that instead? That seems like the default value of the colorpicker anyway. Is that something useful to try?

**Comment by hkirat** [comment]
@aayushsanghavi  You can define a setLine function as follows since I think it doesn't already exist in Codemirror
```js
function setLine(lineNo, newContent, hostEditor) {
    var currentContent = hostEditor._codeMirror;
    var lines = currentContent.split("\n");
    lines[lineNo] = newContent;
    hostEditor._codeMirror.setValue(lines.join("\n"));
}
```
Hope this helps.
You can use this to either include spaces or a default value as suggested by @flukeout

**Comment by aayushsanghavi** [comment]
@hkirat thanks for the hint with setting the content of the hostEditor._codeMirror component. I was actually looking for that when I mentioned that we could add a space and replace it with a color string. Also, if we got off on the wrong foot yesterday, sorry for that.

@flukeout I've added what you suggested. Now, the default color comes written with a new CSS rule of type color. I've also handled the case of an empty color string for a CSS rule. Please test it and let me know if we got it right this time.

Here's how it looks now -
color-picker-5

If you think it is how we need it to work, please let @humphd know so that we can have a final review of the code.

**Comment by flukeout** [comment]
@aayushsanghavi - testing again now, thanks!

**Comment by flukeout** [comment]
Hey @aayushsanghavi - just tested this out and it's working way better! As I understand it, the colorpicker only shows up on ``color`` rules when there is no existing value there, right? It wasn't working on blank rules for ``background:`` for example.

I also found another issue, you can see below...

picker-blank

If I specify a color then close the rule with a ``;`` and launch the colopicker it selects the colorpicker correctly. But if I remove the ``;`` and then add a space and use the picker, it inserts it before the existing color. Can it just select the color already on that line? Cheers!

**Comment by aayushsanghavi** [comment]
@flukeout thanks for testing it.
It actually won't work for an empty background rule because the background rule isn't in the ColorProperties.json file. It will work for all rules in that file. Also, for rules like background and border, we agreed on just having it pop up when the color value is specified and the cursor is on the color value because they take other non color values (background: red no-repeat for example).
And I'm not sure why it isn't work for the other rules in that file.
Also, thanks for pointing out that issue. I'll look into it, it has something to do with the way I'm making the condition checks. Should be an easy fix.

**Comment by aayushsanghavi** [comment]
@flukeout I've made some changes in the condition checks. They should now handle any such case.
I also tried using the color picker on all the rules mentioned in the ColorProperties.json file and they worked fine for me (I tested it on Bramble, so I assume it should work fine on Thimble too).

This is how it looks now (just the issue you pointed out, the rest is the same so I didn't include it in the gif) -

color-picker-6

And for CSS rules like background, border, etc, the color picker will pop up only when the cursor is on the color value. So it will not work for these rules when blank, that's how we intended it to work, right?

**Comment by flukeout** [comment]
Testing again now!

**Comment by humphd** [comment]
@flukeout where did your testing land?

**Comment by flukeout** [comment]
@humphd re-testing now. Will update shortly.

**Comment by flukeout** [comment]
Tested again now - and 👍 - good to go! Nice work @aayushsanghavi !!

**Comment by flukeout** [comment]
@humphd if the code checks out then go ahead and merge please.

**Comment by aayushsanghavi** [comment]
Thanks for testing it @flukeout.

File: src/extensions/default/InlineColorEditor/ColorProperties.json [hunk 14]
```diff
@@ -0,0 +1,13 @@
...
+    "border-color":                {"values": ["inherit"], "type": "color"},
+    "border-bottom-color":         {"values": ["inherit"], "type": "color"},
+    "border-left-color":           {"values": ["inherit"], "type": "color"},
+    "border-right-color":          {"values": ["inherit"], "type": "color"},
+    "border-top-color":            {"values": ["inherit"], "type": "color"},
+    "color":                       {"values": ["inherit"], "type": "color"},
+    "column-rule-color":           {"values": [], "type": "color"},
+    "outline-color":               {"values": ["invert", "inherit"], "type": "color"},
+    "text-decoration-color":       {"values": [], "type": "color"},
+    "text-emphasis-color":         {"values": [], "type": "color"}
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/ColorProperties.json]: I don't think there's any value having `"type": "color"` on every one of these: because they all have it, you might as well get rid of it everywhere, and remove the check below for `type = "color"`.

File: src/extensions/default/InlineColorEditor/main.js [hunk 15]
```diff
@@ -24,11 +24,34 @@
...
-        ExtensionUtils      = brackets.getModule("utils/ExtensionUtils"),
-        InlineColorEditor   = require("InlineColorEditor").InlineColorEditor,
-        ColorUtils          = brackets.getModule("utils/ColorUtils");
+    try {
+        var EditorManager       = brackets.getModule("editor/EditorManager"),
+            ExtensionUtils      = brackets.getModule("utils/ExtensionUtils"),
+            InlineColorEditor   = require("InlineColorEditor").InlineColorEditor,
+            ColorUtils          = brackets.getModule("utils/ColorUtils"),
+            ColorProperties     = require("text!ColorProperties.json"),
+            properties          = JSON.parse(ColorProperties);
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: Let's not but all this in the `try/catch`.  The only thing that might fail is `JSON.parse()`, but even that I'm not too worried about--since this file doesn't change, and we'll catch it in debug builds.  Also, Brackets uses this pattern all over the place:

```js
var properties = JSON.parse(require("text!ColorProperties.json"));
```

So let's just get rid of the `try/catch` block completely.

File: src/extensions/default/InlineColorEditor/main.js [hunk 16]
```diff
@@ -59,7 +82,50 @@ define(function (require, exports, module) {
...
+            var cssPropertyName, semiColonPos, colonPos, colorValue, cursorLineSubstring, firstCharacterPos;
+
+            // Get the css property name after removing spaces and ":" so that we can check for it in the file ColorProperties.json
+            cssPropertyName = cursorLine.split(':')[0].trim();
+
+            if (!cssPropertyName || !properties[cssPropertyName]) {
+                return null;
+            }
+
+            if (properties[cssPropertyName].type === "color") {
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: See above, and let's change this to just `if (properties[cssPropertyName]) {`

File: src/extensions/default/InlineColorEditor/main.js [hunk 17]
```diff
@@ -59,7 +82,50 @@ define(function (require, exports, module) {
...
+                        pos.ch = colonPos + 1 + Math.min(firstCharacterPos,1);
+                        if (semiColonPos !== -1) {
+                            endPos = {line: pos.line, ch: semiColonPos};
+                        } else {
+                            endPos = {line: pos.line, ch: cursorLine.length};
+                        }
+                    } else {
+                         return null;
+                    }
+                } else if (!colorValue) {
```
Comment (humphd) [inline src/extensions/default/InlineColorEditor/main.js]: You can change this to just be `} else {`

**Comment by aayushsanghavi** [comment]
Thanks for the review @humphd!
I've made the changes you suggested. Please have a look and let me know if they're fine.

File: src/extensions/default/InlineColorEditor/main.js [hunk 18]
```diff
@@ -27,8 +27,26 @@ define(function (require, exports, module) {
...
+        ColorUtils          = brackets.getModule("utils/ColorUtils"),
+        properties          = JSON.parse(require("text!ColorProperties.json"));
 
+    var DEFAULT_COLOR = "white";
+
+    /*
+    This function takes a line number, string and the colon position, and writes
+    the default color value at 2 places after the colon position
+     */
+    function setLine(lineNo, newContent, hostEditor, colonPos) {
```
Comment (gideonthomas) [inline src/extensions/default/InlineColorEditor/main.js]: I think it's odd that we're resetting the entire contents of the editor for a single line change when we can just use `replaceRange` instead to add in what we need.

**Comment by aayushsanghavi** [comment]
@gideonthomas would you tell me more about the `replaceRange` function you mentioned earlier.
I would like us to have this issue fixed soon and get the color picker working on Thimble.

File: src/extensions/default/InlineColorEditor/main.js (hunk 18 above)
Comment (gideonthomas) [inline src/extensions/default/InlineColorEditor/main.js]: You can find the docs here: https://codemirror.net/doc/manual.html#api_content. If you Ctrl+F `replaceRange`, you should be able to find it in a bunch of places (esp. in Editor.js)

**Comment by aayushsanghavi** [comment]
A gentle reminder @gideonthomas, please take a look at the patch.

**Comment by gideonthomas** [comment]
@aayushsanghavi thanks! Looks great! Sorry for the delay!
